server:
  applicationContextPath: /*
  adminContextPath: /thinslice-admin/*
  applicationConnectors:
  - type: http
    port: 8086
  adminConnectors:
  - type: http
    port: 8087
  registerDefaultExceptionMappers: true

mongo:
  databaseName: thinslice-dev